version: "3.9"
services:
  telegram-live-search-app:
    container_name: telegram-live-search-app
    restart: unless-stopped
    # network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile.prod
    image: telegram-live-search-app:latest
    ports:
      - 3004:3004
    command: npm start
    volumes:
      - ".:/app"
      - "/app/node_modules"

  # telegram-live-search-app-ngrok:
  #   image: shkoliar/ngrok
  #   container_name: telegram-live-search-app-ngrok
  #   ports:
  #     - 4551:4551
  #   # command:
  #   #   - /bin/sh
  #   #   - -c
  #   #   - |
  #   #     cd /usr/local/bin/
  #   #     ./ngrok authtoken ...
  #   #     ./ngrok http 3000
  #   links:
  #     - telegram-live-search-app
  #   environment:
  #     - DOMAIN=telegram-live-search-app
  #     - PORT=3000
